# -*- coding: utf-8 -*-
"""data_analyst.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/168Crc-GqCe7N3-PImxUvKIH_6TdKWG2h
"""

#Write a for loop that prints all numbers from 1 to 5 using range()
for i in range(1,6):
	print(i)

#Write a for loop that prints only odd numbers between 1 and 10 using the step parameter in range()
for i in range(1,10,2):
  print(i)

#Write a nested for loop that prints the following pattern:
for i in range(3):
  for j  in range(2):
    print (i,j)

#Write a for loop that prints numbers from 1 to 7. If the number is 5, stop the loop immediately using break
for i in range(1,8):
  if  i == 5:
    break
  print(i)