# -*- coding: utf-8 -*-
"""Movie_Theatre_Booking_System.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYh3kOwRzZZ0WVdesZ-36ZE78nTBBfTL
"""

# Total seats available
capacity = 350
remaining_seats = capacity

# Counters for final report
total_bookings = 0
tickets_sold = 0
rejected_bookings = 0

# Main loop (runs until theatre is full or user enters 0)
while remaining_seats > 0:
    tickets = int(input("Enter number of tickets (0 to exit): "))

    # Exit condition
    if tickets == 0:
        break

    # Check if ticket count is valid (1–15)
    if tickets < 1 or tickets > 15:
        print("BOOKING REJECTED - Invalid number of tickets")
        rejected_bookings += 1
        continue   # Skip this booking and go to next loop

    # Check if enough seats are available
    if tickets > remaining_seats:
        print("BOOKING REJECTED - Not enough seats")
        rejected_bookings += 1
        continue

    # Assume booking is valid first
    valid_booking = True

    # Ask age for each person
    for i in range(tickets):
        age = int(input(f"Enter age for person {i+1}: "))

        # If any person is below 12 → reject booking
        if age < 12:
            valid_booking = False

    # If age condition failed
    if not valid_booking:
        print("BOOKING REJECTED - Age restriction")
        rejected_bookings += 1
        continue

    # If everything is valid → confirm booking
    print(f"BOOKING CONFIRMED - {tickets} tickets")

    total_bookings += 1
    tickets_sold += tickets
    remaining_seats -= tickets

    # Stop if theatre is full
    if remaining_seats == 0:
        print("Theatre is now full.")
        break

# Final Report
print("\nFinal Report:")
print("Total Bookings:", total_bookings)
print("Total Tickets Sold:", tickets_sold)
print("Rejected Bookings:", rejected_bookings)
print("Remaining Seats:", remaining_seats)